version: 2.1

orbs:
  node: circleci/node@5

executors:
  sonar-docker:
    docker:
      - image: sonarsource/sonar-scanner-cli:latest
    working_directory: ~/project/Customer_portal/Customer_portal/frontend

jobs:
  sonarqube:
    executor: sonar-docker
    steps:
      - checkout
      - run: |
          # Setting branch name for SonarQube analysis
          SONAR_BRANCH="${CIRCLE_BRANCH:-main}"
          echo "Sonar branch value is: $SONAR_BRANCH"
sonar-scanner \
  -Dsonar.projectKey="$SONAR_PROJECT_KEY" \
  -Dsonar.organization="$SONAR_ORG" \
  -Dsonar.host.url="https://sonarcloud.io" \
  -Dsonar.login="$SONAR_TOKEN" \
  -Dsonar.branch.name="$SONAR_BRANCH" \
  -Dsonar.sources="." \
  -Dsonar.exclusions="**/*.java"


  test-node:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Run Tests
          command: npm test --passWithNoTests --detectOpenHandles

  build-node:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Build Project
          command: npm run build
      - run:
          name: Copy Artifacts
          command: |
            mkdir -p ~/artifacts
            cp -R build dist public .output .next .docusaurus ~/artifacts 2>/dev/null || true
      - store_artifacts:
          path: ~/artifacts
          destination: node-build

workflows:
  build-and-test:
    jobs:
      - test-node
      - sonarqube
      - build-node:
          requires:
            - test-node
