name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
   
    - name: Change to frontend directory
      run: cd Customer_portal/frontend

    # Install dependencies
    - name: Install dependencies
      run: npm install

    # Build the project
    - name: Build project
      run: npm run build --if-present

    # Run tests
    - name: Run tests
      run: npm test
