name: Frontend Build & Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  frontend-check:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]  # Node.js versions you want to check

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Change to frontend directory
      working-directory: Customer_Portal/frontend  # Navigate to frontend directory
      run: pwd  # Just checking the current directory for confirmation

    - name: Install dependencies
      working-directory: Customer_Portal/frontend
      run: npm install  # Installing dependencies

    - name: Build frontend
      working-directory: Customer_Portal/frontend
      run: npm run build --if-present  # Run build if build script exists

    - name: Run frontend tests
      working-directory: Customer_Portal/frontend
      run: npm test  # Run tests for frontend
